apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: pv-vol
spec: 
  accessModes: 
    - ReadOnlyMany 
  capacity: 
    storage: 50Gi 
  gcePersistentDisk:
    pdName: gke-pv
    fsType: ext4
  storageClassName: gcp-disk





